### ISSUE TITLE
Can you describe in detail a sequence of your training phase?

### ISSUE THREAD

**Issue by linhduongtuan** [ethanyanjiali/minChatGPT#8]
Hi Ethan,
I really appreciate your source code and I plan on re-implementing it. However, as I was going through the README.md, I'm unsure about how to begin. Could you please provide me with a detailed, step-by-step explanation of how you trained the minChatGP? I would be grateful for your assistance and I am eagerly awaiting your response.
Linh

**Comment by ethanyanjiali** [comment]
Thnaks Linh. I will work on a more detailed README today. Also need to
clean up the code a bit since it was rushed to meet our class project
deadline.

**Comment by ethanyanjiali** [comment]
Hey @linhduongtuan I updated the readme with more instructions, you can check out this section in README: https://github.com/ethanyanjiali/minChatGPT#get-started

**Comment by linhduongtuan** [comment]
Hi @ethanyanjiali thank you so much for swift responding. I will try your code soon. 
Linh
